name: Запуск тестов и публикация отчета

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Проверить код
        uses: actions/checkout@v3

      - name: Настроить JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Запустить тесты
        run: ./gradlew clean test


