name: Запуск тестов и публикация отчета

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Проверить код
        uses: actions/checkout@v3

      - name: Настроить JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18

      - name: Настроить Selenoid
        uses: Xotabu4/selenoid-github-action@v3

      - name: Запустить тесты
        run: ./gradlew --warning-mode all clean test

      - name: Загрузить историю отчета тестов
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Построить отчет тестов
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Опубликовать отчет тестов
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
